@host = http://0:4321

@uuidOwner = 96c1e6cf-8b44-4366-b35c-75f2303076fc
@uuidOwner = f486ac83-e999-456e-9505-5ceb234016f2

@uuid = 3577c3e1-9d18-45f0-a0aa-c9c4af4c81a3

###

# @name Health Check
# @description Pulsy service Health Check
GET /health

###

# @name Upload File
# @description Upload File to Storage
POST /files
x-consumer-custom-id: {{uuidOwner}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="share.txt"

< ./share.txt
--WebKitFormBoundary--

###

# @name Download File
# @description Download File from Storage
GET /files/{{uuid}}
x-consumer-custom-id: {{uuidOwner}}

###

# @name Update File
# @description Update File to Storage
PUT /files/{{uuid}}
x-consumer-custom-id: {{uuidOwner}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="share.txt"

< ./share.txt
--WebKitFormBoundary--

###

# @name Delete File
# @description Delete File from Storage
DELETE /files/{{uuid}}
x-consumer-custom-id: {{uuidOwner}}

###

# @name Get list of metadata
# @description Get list of metadata of all files
GET /files
x-consumer-custom-id: {{uuidOwner}}

###

# @name Get metadata
# @description Get metadata of specific file
GET /files/{{uuid}}/metadata
x-consumer-custom-id: {{uuidOwner}}

###